# Generated by Antigravity
# Stage 1: Builder
FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim AS builder

WORKDIR /app
ENV UV_COMPILE_BYTECODE=1

# Copy dependency files
COPY pyproject.toml uv.lock ./

# Install dependencies (frozen lockfile) without the project
RUN uv sync --frozen --no-install-project

# Copy source code and config
COPY src ./src
COPY config ./config

# Install the project
RUN uv sync --frozen

# Stage 2: Runner
FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

WORKDIR /app

# Copy the environment from builder
COPY --from=builder /app /app

# Set environment variables
ENV PATH="/app/.venv/bin:$PATH"
ENV XENSERVER_CONFIG=/app/config/clusters.json
ENV PYTHONUNBUFFERED=1

# Entrypoint
ENTRYPOINT ["uv", "run", "--frozen", "xenserver-mcp"]
